source/accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accounts.views import UserProfileView, RegisterView, UserUpdateView

app_name = 'accounts'

urlpatterns = [
    path('<int:pk>/', UserProfileView.as_view(), name="user_profile"),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('registration/', RegisterView.as_view(), name="registration"),
    path('<int:pk>/update/', UserUpdateView.as_view(), name='user_update'),
]

source/main/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin

from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path, include

from webapp.views.ad_views import AdListView, AdCreateView, AdView, AdDeleteView, AdUpdateView, AdReviewListView, AdApproveView
from webapp.views.api import set_status_accept, set_status_reject

app_name = 'webapp'

api_urlpatterns = [
    path("accept/ad/", set_status_accept),
    path("reject/ad/", set_status_reject),
]

urlpatterns = [
    path('', AdListView.as_view(), name="index"),
    path('create/', AdCreateView.as_view(), name='ad_create'),
    path('<int:pk>/', AdView.as_view(), name='ad_view'),
    path('<int:pk>/delete/', AdDeleteView.as_view(), name="ad_delete"),
    path('<int:pk>/update/', AdUpdateView.as_view(), name='ad_update'),
    path('ad_review/', AdReviewListView.as_view(), name='ad_review_list'),
    path('<int:pk>/approve/', AdApproveView.as_view(), name='ad_approve_detail'),
    path("api/", include(api_urlpatterns))
]

source/webapp/models.py
import datetime

from django.contrib.auth import get_user_model
from django.db import models


User = get_user_model()

AD_STATUS = (('For moderation', 'На модерацию'), ('Published', 'Опубликовано'), ('Rejected', 'Отклонено'))


class Ad(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='ads', verbose_name='Автор')
    title = models.CharField(max_length=50, null=False, blank=False, verbose_name='Заголовок')
    text = models.TextField(max_length=500, null=False, blank=False, verbose_name='Описание')
    category = models.ForeignKey('webapp.Category', on_delete=models.CASCADE, related_name='ads', verbose_name='Категория')
    status = models.CharField(max_length=50, default='For moderation', choices=AD_STATUS, verbose_name='Статус')
    photo = models.ImageField(upload_to="uploads/", null=True, blank=True, verbose_name='Фото')
    price = models.PositiveIntegerField(null=True, blank=True, verbose_name='Цена')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Дата изменения")
    published_at = models.DateTimeField(null=True, blank=True, verbose_name="Дата публикации")
    is_deleted = models.BooleanField(null=True, blank=True, default=False, verbose_name='Удален')

    def soft_delete(self):
        self.is_deleted = True
        self.save()

    def set_status_reject(self):
        self.status = "Rejected"
        self.save()

    def set_status_approve(self):
        self.status = "Published"
        self.published_at = datetime.datetime.now()
        self.save()

    class Meta:
        db_table = 'ads'
        verbose_name = 'Объявление'
        verbose_name_plural = 'Объявления'

    def __str__(self):
        return f'{self.id}.{self.author}: {self.title}'


class Category(models.Model):
    name = models.CharField(max_length=50, null=False, blank=False, verbose_name='Название категории')

    class Meta:
        db_table = 'categories'
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return f'{self.name}'

source/webapp/forms.py
from django import forms


from webapp.models import Ad


class AdForm(forms.ModelForm):
    class Meta:
        model = Ad
        fields = ('title', 'text', 'photo', 'category', 'price')


class SearchForm(forms.Form):
    search = forms.CharField(max_length=30, required=False, label="Найти")

source/webapp/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, DeleteView, UpdateView

from webapp.forms import AdForm
from webapp.models import Ad


class AdListView(ListView):
    model = Ad
    template_name = 'index.html'
    context_object_name = 'ads'
    ordering = ('-created_at',)
    paginate_by = 3
    paginate_orphans = 0

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(status='Published').filter(is_deleted=False)
        return queryset


class AdCreateView(LoginRequiredMixin, CreateView):
    model = Ad
    form_class = AdForm
    template_name = 'ad_create.html'

    def form_valid(self, form):
        ad = form.save(commit=False)
        ad.author = self.request.user
        ad.save()
        return redirect('webapp:index')


class AdView(DetailView):
    model = Ad
    context_object_name = 'ad'
    template_name = 'ad_view.html'


class AdDeleteView(PermissionRequiredMixin, DeleteView):
    model = Ad
    context_object_name = 'ad'
    template_name = 'ad_delete.html'
    success_url = reverse_lazy('webapp:index')

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.soft_delete()
        messages.success(self.request, f'Объявление: {self.object.title} успешно удален!')
        return HttpResponseRedirect(self.get_success_url())

    def has_permission(self):
        return self.get_object().author == self.request.user


class AdUpdateView(PermissionRequiredMixin, UpdateView):
    model = Ad
    form_class = AdForm
    context_object_name = 'ad'
    template_name = 'ad_create.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(Q(status='Published') & Q(is_deleted=False))
        return queryset

    def has_permission(self):
        return self.get_object().author == self.request.user

    def form_valid(self, form):
        ad = form.save(commit=False)
        ad.status = 'For moderation'
        ad.save()
        return redirect('webapp:index')


class AdReviewListView(PermissionRequiredMixin, ListView):
    model = Ad
    template_name = 'review.html'
    context_object_name = 'ads'
    ordering = ('-created_at',)
    paginate_by = 3
    paginate_orphans = 0

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(status='For moderation').filter(is_deleted=False)
        return queryset

    def has_permission(self):
        return self.request.user.is_staff


class AdApproveView(PermissionRequiredMixin, DetailView):
    model = Ad
    template_name = 'ad_approve.html'
    context_object_name = 'ad'

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(Q(status='For moderation') & Q(is_deleted=False))
        return queryset

    def has_permission(self):
        return self.request.user.is_staff

source/webapp/views/ad_views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, DeleteView, UpdateView

from webapp.forms import AdForm
from webapp.models import Ad
from webapp.views.search_view import SearchView


class AdListView(SearchView):
    model = Ad
    template_name = 'index.html'
    context_object_name = 'ads'
    ordering = ('-created_at',)
    paginate_by = 3
    paginate_orphans = 0
    search_fields = ["title__icontains", "text__icontains"]

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(status='Published').filter(is_deleted=False)
        return queryset


class AdCreateView(LoginRequiredMixin, CreateView):
    model = Ad
    form_class = AdForm
    template_name = 'ad_create.html'

    def form_valid(self, form):
        ad = form.save(commit=False)
        ad.author = self.request.user
        ad.save()
        return redirect('webapp:index')


class AdView(DetailView):
    model = Ad
    context_object_name = 'ad'
    template_name = 'ad_view.html'


class AdDeleteView(PermissionRequiredMixin, DeleteView):
    model = Ad
    context_object_name = 'ad'
    template_name = 'ad_delete.html'
    success_url = reverse_lazy('webapp:index')

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.soft_delete()
        messages.success(self.request, f'Объявление: {self.object.title} успешно удален!')
        return HttpResponseRedirect(self.get_success_url())

    def has_permission(self):
        return self.get_object().author == self.request.user


class AdUpdateView(PermissionRequiredMixin, UpdateView):
    model = Ad
    form_class = AdForm
    context_object_name = 'ad'
    template_name = 'ad_create.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(Q(status='Published') & Q(is_deleted=False))
        return queryset

    def has_permission(self):
        return self.get_object().author == self.request.user

    def form_valid(self, form):
        ad = form.save(commit=False)
        ad.status = 'For moderation'
        ad.save()
        return redirect('webapp:index')


class AdReviewListView(PermissionRequiredMixin, SearchView):
    model = Ad
    template_name = 'review.html'
    context_object_name = 'ads'
    ordering = ('-created_at',)
    paginate_by = 3
    paginate_orphans = 0
    search_fields = ["title__icontains", "text__icontains"]

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(status='For moderation').filter(is_deleted=False)
        return queryset

    def has_permission(self):
        return self.request.user.is_staff


class AdApproveView(PermissionRequiredMixin, DetailView):
    model = Ad
    template_name = 'ad_approve.html'
    context_object_name = 'ad'

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(Q(status='For moderation') & Q(is_deleted=False))
        return queryset

    def has_permission(self):
        return self.request.user.is_staff

source/webapp/views/api.py
import http
import json

from django.http import JsonResponse

from webapp.models import Ad


def set_status_accept(request):
    if request.method == "POST" and request.user.is_staff:
        try:
            if request.body:
                body = json.loads(request.body)
                if body["status"] == "accept":
                    Ad.objects.get(pk=body["id"]).set_status_approve()
                    return JsonResponse(data={"status": "success"}, status=http.HTTPStatus.OK)
        except:
            return JsonResponse(data={"status": "failed"}, status=http.HTTPStatus.NOT_FOUND)


def set_status_reject(request):
    if request.method == "POST" and request.user.is_staff:
        try:
            if request.body:
                body = json.loads(request.body)
                if body["status"] == "reject":
                    Ad.objects.get(pk=body["id"]).set_status_reject()
                    return JsonResponse(data={"status": "success"}, status=http.HTTPStatus.OK)
        except:
            return JsonResponse(data={"status": "failed"}, status=http.HTTPStatus.NOT_FOUND)

source/webapp/views/search_view.py
from django.db.models import Q
from django.views.generic import ListView

from webapp.forms import SearchForm


class SearchView(ListView):
    search_form_class = SearchForm
    search_form_field = "search"
    search_fields = []

    def get(self, request, *args, **kwargs):
        self.form = self.get_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            query = self.get_query()
            queryset = queryset.filter(query)
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = self.search_form_class()
        if self.search_value:
            context['form'] = self.search_form_class(initial={self.search_form_field: self.search_value})
            context[self.search_form_field] = self.search_value
        return context

    def get_form(self):
        return self.search_form_class(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data.get(self.search_form_field)

    def get_query(self):
        query = Q()
        for field in self.search_fields:
            kwargs = {field: self.search_value}
            query = query | Q(**kwargs)
        return query

source/webapp/templates/partial/ad_list.html
{% load static %}

<div class="row my-3">
        {% for ad in ads %}
            <div class="col-12 col-md-4 col-lg-4">
                <div class="card mb-3">
                    {% if ad.photo %}
                        <img src="{{ ad.photo.url  }}" class="card-img-top" alt="photo">
                    {% else %}
                        <img src="{% static 'img/No_picture.jpg' %}" class="card-img-top" alt="photo">
                    {% endif %}
                    <div class="card-body">
                        <h5 class="card-title">{{ ad.title }}</h5>
                        <p class="card-text">Автор:<a style="text-decoration: none" href="{% url 'accounts:user_profile' ad.author.pk %}">
                    {{ ad.author.first_name | capfirst }}</a></p>
                        <p class="card-text">Телефон: {{ ad.author.phone }}</p>
                        <p class="card-text">Категория: {{ ad.category }}</p>
                        <p class="card-text">Цена: {{ ad.price|default:"" }}</p>
                        <p class="card-text">Описание: {{ ad.text }}</p>
                        <p class="card-text">status: {{ ad.status }}</p>
                        {% if more %}
                            <div class="btn-group">
                                <a class="btn btn-success" href="{% url 'webapp:ad_view' ad.pk %}">Просмотр</a>
                                {% if ad.author == request.user %}
                                    {% if ad.status != 'Rejected'%}
                                        <a class="btn btn-primary" href="{% url 'webapp:ad_update' ad.pk %}">Изменить</a>
                                    {%  endif %}
                                    <a class="btn btn-danger" href="{% url 'webapp:ad_delete' ad.pk %}">Удалить</a>
                                {%  endif %}
                            </div>
                            {% endif %}
                        {% if approve %}
                            <a href="{% url 'webapp:ad_approve_detail' ad.pk %}" type="button" class="btn btn-outline-primary ml-0 pl-0 mt-auto pt-auto">Просмотр</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
</div>

{% if is_paginated %}
   {% include 'partial/pagination.html' %}
{% endif %}

source/webapp/templates/partial/ad_view.html
{% load static %}

<div class="card mb-3" >
      <div class="row g-0">
        <div class="col-md-4">
            {% if ad.photo %}
                <img src="{{ ad.photo.url  }}" class="img-fluid rounded-start" alt="photo">
            {% else %}
                <img src="{% static 'img/No_picture.jpg' %}" class="img-fluid rounded-start" alt="photo">
            {% endif %}
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h3 class="card-title">Автор: <a href="{% url 'accounts:user_profile' ad.author.pk %}">{{ ad.author.first_name | capfirst }}</a></h3>
              <p class="h6">Телефон: {{ ad.author.phone }}</p>
              <hr>
              <h5 class="card-title">{{ ad.title }}</h5>
            <p class="card-text">{{ ad.text }}</p>
            <p class="h6">Цена: {{ ad.price|default:"" }}</p>
            <p class="card-text"><small class="text-muted">{{ ad.published_at }}</small></p>
              <div class="btn-group">
                  {% if ad.author == request.user %}
                      {% if ad.status != 'Rejected'%}
                          <a class="btn btn-primary" href="{% url 'webapp:ad_update' ad.pk %}">Изменить</a>
                      {%  endif %}
                      <a class="btn btn-danger" href="{% url 'webapp:ad_delete' ad.pk %}">Удалить</a>
                  {%  endif %}
              </div>
          </div>
        </div>
      </div>
    </div>

source/webapp/templates/partial/form.html
{% if not fields_only %}
    {% csrf_token %}
{% endif %}

{% for error in form.non_field_errors %}
   <p class="text-danger">{{ error }}</p>
{% endfor %}

{% for field in form %}
    <p><label for="{{ field.id_for_label }}">{{ field.label }}</label></p>
    {% for error in field.errors %}
        <p class="text-danger">{{ error }}</p>
    {% endfor %}
    {{ field }}
{% endfor %}

<br>
{% if not fields_only %}
    <input type="submit" value={{ button_text|default:"Save" }} >
{% endif %}

source/webapp/templates/partial/pagination.html
<div class="pagination">
    <span class="step-links">
        <a href="?page=1">&laquo; В начало</a>
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">Назад</a>
        {% else %}
            <span class="page-disabled">Назад</span>
        {% endif %}
        <form class="current-page" method="get">
            <label for="page">
                Страница <input type="text" name="page" id="page" value="{{ page_obj.number }}">
                из {{ page_obj.paginator.num_pages }}.
            </label>
        </form>
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Далее</a>
        {% else %}
            <span class="page-disabled">Далее</span>
        {% endif %}
        <a href="?page={{ page_obj.paginator.num_pages }}">В конец &raquo;</a>
    </span>
</div>

source/webapp/templates/partial/simple_search.html
<form class="text-center mt-3 mb-2" action="" method="GET">
    <label for="{{ form.search.id_for_label }}">{{ form.search.label }}:</label>
    {{ form.search }}
    <input type="submit" value="Поиск">
    {% for error in form.search.errors %}
        <p class="form-error">{{ error }}</p>
    {% endfor %}
</form>